# Einkommenssteuer Plots

In [1]:
import pandas as pd
%matplotlib inline

Grundsätzlich schauen: Macht die Abstufung zwischen den Einkommen Sinn?

## Alleinstehende

#### Meine Fragestellungen:
- Gibt es markante Verschiebungen bei den Einkommensklassen und im Total zwischen 2007 und 2017? Prozentmässig?
- Vergleich Ehepaare - Alleinstehende: Wer ist reicher?
- Wie hohe Steuern bezahlte der durchschnittliche (oder mediane) Alleinstehende pro Jahr und wie hat sich das verändert? (Das dann mit den Ehepaaren vergleichen)
- Hier noch das Wachstum des Alleinstehendenabzugs erwähnen, das dann zeigt: Nicht die wirklich Alleinstehenden haben gewachsen, sondern die Leute in Mehrpersonenhaushalten. Das können auch Altersheime oder WGs sein, oder aber Konkubinatspaare. Hier nur die Prozentzahl nehmen, da die Berechnungen des Kantons auf anderen Zahlen beruhen (Veranlagungsstand) als die hier vorliegenden.

### 1. Anzahl

In [2]:
Steuerpflichtige_Alleinstehende = pd.read_csv('Steuerpflichtige Alleinstehende 2007 bis 2017')
Steuerpflichtige_Alleinstehende

,Unnamed: 0,Einkommen 0 CHF,Einkommen 100-20000 CHF,Einkommen 20100-40000 CHF,Einkommen 40100-60000 CHF,Einkommen 60100-80000 CHF,Einkommen 80100-100000 CHF,Einkommen 100100-125000 CHF,Einkommen 125100-150000 CHF,Einkommen 150100-175000 CHF,Einkommen 175100-200000 CHF,Einkommen 200100-250000 CHF,Einkommen 250100-300000 CHF,Einkommen ab 300100-400000 CHF,Einkommen 400100-500000 CHF,Einkommen 500100-750000 CHF,Einkommen 750100-1000000 CHF,Einkommen ab 1000100 CHF,Total
0,Anzahl Alleinstehende 2007,96546,91488,111731,63313,21505,7871,3626,1537,692,456,472,268,210,90,71,27,46,399949
1,Anzahl Alleinstehende 2008,95464,90431,111909,67022,23396,8605,4034,1726,778,451,512,243,225,105,92,24,46,405063
2,Anzahl Alleinstehende 2009,98157,90024,111858,68454,23752,8963,4252,1782,837,484,519,266,227,108,94,37,45,409859
3,Anzahl Alleinstehende 2010,98843,91013,112617,69523,24659,9311,4439,1802,889,485,551,249,264,105,107,31,56,414944
4,Anzahl Alleinstehende 2011,99323,92449,112815,71277,25519,9661,4679,1866,938,497,581,298,270,112,94,33,50,420462
5,Anzahl Alleinstehende 2012,99844,93077,113124,73723,26567,10076,4842,1955,938,550,565,305,261,126,94,39,48,426134
6,Anzahl Alleinstehende 2013,100005,93874,113936,75799,27583,10611,5131,1994,946,547,582,323,277,113,96,41,53,431911
7,Anzahl Alleinstehende 2014,99385,92256,113171,80200,29252,10858,5305,2102,1014,558,620,343,291,132,110,30,67,435694
8,Anzahl Alleinstehende 2015,98952,93211,113962,81663,30097,11417,5363,2193,1075,587,615,357,311,123,127,41,64,440158
9,Anzahl Alleinstehende 2016,98826,93568,112884,83987,31397,11860,5656,2331,1097,644,616,351,314,163,127,49,73,443943
10,Anzahl Alleinstehende 2017,98122,94229,113695,85216,32138,12301,5758,2361,1162,672,664,355,338,131,130,61,71,447404

### 2. Steuerbetrag

In [3]:
Steuerbetrag_Alleinstehende = pd.read_csv('Steuerbetrag Alleinstehende 2007 bis 2017')
Steuerbetrag_Alleinstehende

,Unnamed: 0,Einkommen 0 CHF,Einkommen 100-20000 CHF,Einkommen 20100-40000 CHF,Einkommen 40100-60000 CHF,Einkommen 60100-80000 CHF,Einkommen 80100-100000 CHF,Einkommen 100100-125000 CHF,Einkommen 125100-150000 CHF,Einkommen 150100-175000 CHF,Einkommen 175100-200000 CHF,Einkommen 200100-250000 CHF,Einkommen 250100-300000 CHF,Einkommen ab 300100-400000 CHF,Einkommen 400100-500000 CHF,Einkommen 500100-750000 CHF,Einkommen 750100-1000000 CHF,Einkommen ab 1000100 CHF,Total
0,Betrag Kantonssteuer Alleinstehende 2007,0,90950139,385187702,379035625,195074286,97784261,58718513,31906800,17585474,13772337,17405488,12496769,12751283,7186064,7825985,4285037,19573493,1351539258
1,Betrag Kantonssteuer Alleinstehende 2008,0,86318137,374832754,388918563,205355987,103294496,62934943,34577778,19092963,13099531,17978035,10752995,12952995,7908679,9147121,3433222,16675076,1367273276
2,Betrag Kantonssteuer Alleinstehende 2009,0,88338206,384084678,405090577,211770331,109244840,67786087,36200306,20819783,14260837,18565955,11939936,13063968,8026449,9736293,4917342,20812927,1424658517
3,Betrag Kantonssteuer Alleinstehende 2010,0,89134497,387448744,411438765,219516780,113563739,70849301,36460883,21987180,14324730,19581665,11107413,15067716,7868023,10482282,4533823,24746213,1458111753
4,Betrag Kantonssteuer Alleinstehende 2011,0,89593826,386590727,420372900,225979453,117024652,74029432,37768577,23154760,14465303,20142071,13227831,15378306,8126841,9077537,4863219,21730361,1481525796
5,Betrag Kantonssteuer Alleinstehende 2012,0,89209798,381770842,426368798,229802120,119023855,74807063,38790216,22612132,15749647,19378114,13120995,14610237,9018498,8930287,5679589,22871996,1491744187
6,Betrag Kantonssteuer Alleinstehende 2013,0,89399240,384721739,438673960,238463230,125271527,79299217,39510080,22872654,15511439,20044606,13975231,15297019,7978973,9478729,5951401,27179700,1533628746
7,Betrag Kantonssteuer Alleinstehende 2014,0,87738102,383569866,464860443,252746368,127889121,81984195,41614421,24357430,15859983,21378001,14961726,16064251,9444124,10670618,4339893,30730814,1588209358
8,Betrag Kantonssteuer Alleinstehende 2015,0,88479622,386866827,473686001,260199398,134492790,82809302,43436129,25698477,16719692,21397529,15192263,17287016,8879784,12143474,5921848,33463721,1626673872
9,Betrag Kantonssteuer Alleinstehende 2016,0,88250234,384195582,487167147,271510743,139472138,87160123,46079577,26216858,18287375,21411053,15038820,17101052,11983456,12024194,6647677,31664874,1664210903
10,Betrag Kantonssteuer Alleinstehende 2017,0,88757629,386899652,494512428,277680349,144802932,88811052,46438745,27790797,19016473,22645222,15094371,18660201,9667518,12001375,8304838,31198938,1692282521

## Ehepaare

#### Meine Fragestellungen:
- Gibt es markante Verschiebungen bei den Einkommensklassen und im Total zwischen 2007 und 2017? Prozentmässig?
- Vergleich Ehepaare - Alleinstehende: Wer ist reicher?
- Wie hohe Steuern bezahlte das durchschnittliche (oder mediane) Ehepaar pro Jahr und wie hat sich das verändert? (Das dann mit den Alleinstehenden vergleichen. Aber Achtung: Ehepaare durch zwei, Alleinstehende oft dann mal zwei, weil viel Konkubinat und so) 
- So würde man evtl auch sehen, ab welchem Einkommen die Heiratsstrafe im Kanton Bern zum Tragen kommt, sprich: Ab welchem Einkommen jeder Einzelne höhere Steuern bezahlt, wenn er verheiratet ist.

### 1. Anzahl

In [5]:
Steuerpflichtige_Ehepaare = pd.read_csv('Steuerpflichtige Ehepaare 2007 bis 2017')
Steuerpflichtige_Ehepaare

,Unnamed: 0,Einkommen 0 CHF,Einkommen 100-20000 CHF,Einkommen 20100-40000 CHF,Einkommen 40100-60000 CHF,Einkommen 60100-80000 CHF,Einkommen 80100-100000 CHF,Einkommen 100100-125000 CHF,Einkommen 125100-150000 CHF,Einkommen 150100-175000 CHF,Einkommen 175100-200000 CHF,Einkommen 200100-250000 CHF,Einkommen 250100-300000 CHF,Einkommen ab 300100-400000 CHF,Einkommen 400100-500000 CHF,Einkommen 500100-750000 CHF,Einkommen 750100-1000000 CHF,Einkommen ab 1000100 CHF,Total
0,Anzahl Ehepaare 2007,16092,26479,44385,51389,38829,21638,13322,6346,3216,1835,1828,914,826,378,345,117,122,228061
1,Anzahl Ehepaare 2008,16064,25347,42438,50861,39521,22758,14191,6732,3366,1908,2046,985,889,377,357,105,130,228075
2,Anzahl Ehepaare 2009,16566,27006,43077,49593,38474,22238,13916,6933,3509,1889,1976,1022,855,394,361,109,159,228077
3,Anzahl Ehepaare 2010,16727,26648,42105,49103,38567,22487,14410,7121,3559,2044,2059,991,917,430,382,122,160,227832
4,Anzahl Ehepaare 2011,16703,27128,41676,48512,38481,22924,14663,7209,3606,2034,2206,1033,962,392,418,119,167,228233
5,Anzahl Ehepaare 2012,16877,27277,40911,48172,38566,23375,14841,7384,3729,2059,2254,1068,970,436,392,125,157,228593
6,Anzahl Ehepaare 2013,17007,27536,40599,47667,38606,23434,15222,7504,3859,2196,2172,1109,1025,437,405,123,153,229054
7,Anzahl Ehepaare 2014,16631,26423,38957,46998,39477,24823,15961,7912,4034,2252,2408,1163,1017,480,402,128,168,229234
8,Anzahl Ehepaare 2015,16263,26592,38056,46847,39493,25219,16283,8186,4242,2306,2396,1147,1081,509,424,113,197,229354
9,Anzahl Ehepaare 2016,15981,25772,37516,46072,39981,25456,16874,8334,4312,2506,2446,1225,1158,480,453,131,196,228893
10,Anzahl Ehepaare 2017,15453,25764,36622,46030,40397,25502,17242,8473,4465,2490,2582,1244,1164,539,467,145,218,228797

### 2. Steuerbetrag

In [1]:
Steuerbetrag_Ehepaare = pd.read_csv('Steuerbetrag Ehepaare 2007 bis 2017')
Steuerbetrag_Ehepaare

NameError: name 'pd' is not defined