# Gewinnsteuer Plots

In [1]:
import pandas as pd
%matplotlib inline

## Betrag Kantonssteuer Firmen

In [2]:
Betrag_Kantonssteuer_Firmen = pd.read_csv('Betrag Kantonssteuer Firmen 2007 bis 2017')
Betrag_Kantonssteuer_Firmen

,Unnamed: 0,Steuerbarer Gewinn 0-10000 CHF,Steuerbarer Gewinn 10100-50000 CHF,Steuerbarer Gewinn 50100-250000 CHF,Steuerbarer Gewinn ab 250100,Total Steuerbetrag
0,Betrag Kantonssteuer 2007 in CHF,996701,7654106,28215316,487465494,524331616
1,Betrag Kantonssteuer 2008 in CHF,1270557,7609731,29853096,391904294,430637678
2,Betrag Kantonssteuer 2009 in CHF,1309193,8020546,32339760,431058562,472728062
3,Betrag Kantonssteuer 2010 in CHF,1051519,8379718,35558173,388354588,433343998
4,Betrag Kantonssteuer 2011 in CHF,953215,8743197,37792190,401481456,448970058
5,Betrag Kantonssteuer 2012 in CHF,988128,8889203,39082269,446332012,495291612
6,Betrag Kantonssteuer 2013 in CHF,1120619,9525772,41375861,479217253,531239504
7,Betrag Kantonssteuer 2014 in CHF,1139949,10214132,43823295,487021441,542198817
8,Betrag Kantonssteuer 2015 in CHF,1021922,10091127,45625213,487789059,544527320
9,Betrag Kantonssteuer 2016 in CHF,1077015,10153766,46507243,514703383,572441407
10,Betrag Kantonssteuer 2017 in CHF,1077016,10928683,48346317,527611474,587963490

### Meine Fragestellungen

- Wie hoch ist der Anteil, den die gewinnstärksten Firmen pro Jahr am Totalbetrag haben? Wie hat sich dieser Anteil in Prozent in diesen 10 Jahren entwickelt? Der Weg dorthin = (100 : Total * Gewinn ab 250100)... und neue Spalte erstellen: df['TOV%'] = df['TOV'] / df['GP']

- Nicht vergessen, in der Geschichte zu erwähnen, dass sie ab 2015 die höchsten gesondert ausgegeben haben und dass sich so natürlich auch Politik machen lässt.

- Wie stark haben die gewinnstarken Firmen im Vergleich zu den anderen über die Jahre hinweg zugelegt? Der Weg dorthin: a) Betrag 2017 minus Betrag 2007; dann b) 100 : Betrag 2017 * das Resultat aus a)... und neue Spalte erstellen: df['TOV%'] = df['TOV'] / df['GP']

- Wenn alle gewinnstarken Firmen gleich viel Steuern zahlen würden: Wie hoch wäre dieser Betrag pro Firma? Und wie hat sich dieser in den 10 Jahren entwickelt? Der Weg dorthin: Die Anzahl Steuerzahler gewinnstärkste Firmen mit dem Betrag der Gewinnstärksten Firmen zusammenführen (so wie für die Orginal-Dataframes gemacht). Dann Betrag durch Anzahl Firma. Und neue Spalte erstellen. Und die plotten.

## Steuerpflichtige Firmen

In [3]:
Steuerpflichtige_Firmen = pd.read_csv('Steuerpflichtige Firmen 2007 bis 2017')
Steuerpflichtige_Firmen

,Unnamed: 0,Steuerbarer Gewinn 0-10000 CHF,Steuerbarer Gewinn 10100-50000 CHF,Steuerbarer Gewinn 50100-250000 CHF,Steuerbarer Gewinn ab 250100,Total Steuerpflichtige
0,Anzahl Steuerpflichtige 2007,18759,4028,2636,1723,27146
1,Anzahl Steuerpflichtige 2008,19165,4172,2871,1764,27972
2,Anzahl Steuerpflichtige 2009,19749,4238,2992,1833,28812
3,Anzahl Steuerpflichtige 2010,21101,4270,3302,2028,30701
4,Anzahl Steuerpflichtige 2011,21061,4659,3581,2148,31449
5,Anzahl Steuerpflichtige 2012,21770,4759,3746,2276,32551
6,Anzahl Steuerpflichtige 2013,22561,4806,3926,2332,33625
7,Anzahl Steuerpflichtige 2014,23123,5130,4114,2416,34783
8,Anzahl Steuerpflichtige 2015,23673,5331,4341,2493,35838
9,Anzahl Steuerpflichtige 2016,24450,5493,4503,2589,37035
10,Anzahl Steuerpflichtige 2017,24918,5787,4660,2707,38072

### Meine Fragestellungen

- Welchen Anteil machen die gewinnstärksten Firmen aus? Wie hat sich dieser Anteil in Prozent in diesen 10 Jahren entwickelt? Der Weg dorthin = (100 : Total * Gewinn ab 250100)... und neue Spalte erstellen: df['TOV%'] = df['TOV'] / df['GP']. diese plotten.

- Wie stark haben die gewinnstarken Firmen im Vergleich zu den anderen über die Jahre hinweg zugelegt? Der Weg dorthin: a) Anzahl 2017 minus Anzahl 2007; dann b) 100 : Anzahl 2017 * das Resultat aus a)... und neue Spalte erstellen: df['TOV%'] = df['TOV'] / df['GP']

- Diese beiden Sachen kann ich dann im Text miteinander vergleichen. 

- Wenn alle gewinnstarken Firmen gleich viel Steuern zahlen würden: Wie hoch wäre dieser Betrag pro Firma? Und wie hat sich dieser in den 10 Jahren entwickelt? Der Weg dorthin: Die Anzahl Steuerzahler gewinnstärkste Firmen mit dem Betrag der Gewinnstärksten Firmen zusammenführen (so wie für die Orginal-Dataframes gemacht). Dann Betrag durch Anzahl Firma. Und neue Spalte erstellen. Und die plotten. (siehe auch oben)