# Erster Test Gewinnsteuer

Hier experimentiere ich mit dem ersten PDF und schaue, welche Bugs da drin sind. 

Mein Ziel ist es, ein Dataframe zu erstellen ganz am Schluss, in dem die Jahre der Index sind und ich in den Kolonnen mit den Gewinnen rumtanzen kann. 

Ich schaue mal, in welche möglichst sinnvolle Form ich das hier bringen kann für ein Jahr. Eventuell so, dass ich alles auf einer Zeile habe mit dem Jahr als Index.

In [31]:
import camelot
import tabula
import pandas as pd

#### Dataframe einlesen

In [32]:
Firmen_2007 = camelot.read_pdf("Firmen_2007.pdf", flavor='stream', pages='all', table_areas=['0,842,595,0'])

In [33]:
Firmen_2007[0].df

,0,1,2,3,4,5
0,,,,Gewinn- und Kapitalsteuern der Juristischen Pe...,,
1,,,Statistique de l'impôt cantonal: bénéfice/capi...,,,
2,,Kantonssteuerstatistik: Gewinn/Kapital der jur...,,,,
3,,Statistique de l'impôt cantonal: bénéfice/capi...,,,,
4,,Gewinnsteuern: Anzahl und Betrag nach Gewinn u...,,,,
5,,steuerbarer Gewinn [CHF],,,Kapitalgesellschaften,"Genossenschaften, Vereine"
6,,,,,,und Übrige
7,,,,,Beträge,Beträge
8,,,,Anzahl,,Anzahl
9,von,,bis,,Kantonssteuer,Kantonssteuer
10,,,,Steuerpflichtige,,Steuerpflichtige
11,,,,,[CHF],[CHF]
12,,0,10'000,18'759,996'701,7'098\n \n73'685
13,,10'100,50'000,4'028,7'654'106,258\n \n367'378
14,,50'100,250'000,2'636,28'215'316,93\n \n594'332
15,,250'100,+,1'723,487'465'494,31\n \n1'057'921
16,,Total,,27'146,524'331'616,7'480\n \n2'093'316
17,,Kapitalsteuern: Anzahl und Betrag nach Kapital...,,,,
18,,steuerbares Kapital,,,Kapitalgesellschaften,"Genossenschaften, Vereine"
19,,[CHF 1'000],,,,und Übrige
20,,,,,Beträge,Beträge
21,,,,Anzahl,,Anzahl
22,von,,bis,,Kantonssteuer,Kantonssteuer
23,,,,Steuerpflichtige,,Steuerpflichtige
24,,,,,[CHF],[CHF]
25,,0,100'000,12'940,496'856,5'669\n \n27'227
26,,100'100,500'000,8'429,1'761'321,1'278\n \n250'021
27,,500'100,1'000'000,2'283,1'413'350,197\n \n126'036
28,,1'000'100,+,3'494,32'203'927,336\n \n1'317'343
29,,Total,,27'146,35'875'454,7'480\n \n1'720'627
30,"Steuerverwaltung des Kantons Bern, www.be.ch/...",,,,,

#### Dataframe benennen

In [34]:
test_df = Firmen_2007[0].df
test_df

,0,1,2,3,4,5
0,,,,Gewinn- und Kapitalsteuern der Juristischen Pe...,,
1,,,Statistique de l'impôt cantonal: bénéfice/capi...,,,
2,,Kantonssteuerstatistik: Gewinn/Kapital der jur...,,,,
3,,Statistique de l'impôt cantonal: bénéfice/capi...,,,,
4,,Gewinnsteuern: Anzahl und Betrag nach Gewinn u...,,,,
5,,steuerbarer Gewinn [CHF],,,Kapitalgesellschaften,"Genossenschaften, Vereine"
6,,,,,,und Übrige
7,,,,,Beträge,Beträge
8,,,,Anzahl,,Anzahl
9,von,,bis,,Kantonssteuer,Kantonssteuer
10,,,,Steuerpflichtige,,Steuerpflichtige
11,,,,,[CHF],[CHF]
12,,0,10'000,18'759,996'701,7'098\n \n73'685
13,,10'100,50'000,4'028,7'654'106,258\n \n367'378
14,,50'100,250'000,2'636,28'215'316,93\n \n594'332
15,,250'100,+,1'723,487'465'494,31\n \n1'057'921
16,,Total,,27'146,524'331'616,7'480\n \n2'093'316
17,,Kapitalsteuern: Anzahl und Betrag nach Kapital...,,,,
18,,steuerbares Kapital,,,Kapitalgesellschaften,"Genossenschaften, Vereine"
19,,[CHF 1'000],,,,und Übrige
20,,,,,Beträge,Beträge
21,,,,Anzahl,,Anzahl
22,von,,bis,,Kantonssteuer,Kantonssteuer
23,,,,Steuerpflichtige,,Steuerpflichtige
24,,,,,[CHF],[CHF]
25,,0,100'000,12'940,496'856,5'669\n \n27'227
26,,100'100,500'000,8'429,1'761'321,1'278\n \n250'021
27,,500'100,1'000'000,2'283,1'413'350,197\n \n126'036
28,,1'000'100,+,3'494,32'203'927,336\n \n1'317'343
29,,Total,,27'146,35'875'454,7'480\n \n1'720'627
30,"Steuerverwaltung des Kantons Bern, www.be.ch/...",,,,,

## Dataframe bearbeiten

#### Oberste Zeilen wegschneiden

In [35]:
Firmen_07 = test_df[12:]
Firmen_07.head(5)

   0        1        2       3            4                               5
12          0   10'000  18'759      996'701  7'098\n               \n73'685
13     10'100   50'000   4'028    7'654'106     258\n             \n367'378
14     50'100  250'000   2'636   28'215'316      93\n             \n594'332
15    250'100        +   1'723  487'465'494       31\n          \n1'057'921
16      Total           27'146  524'331'616    7'480\n          \n2'093'316

Und diese fünf sind eigentlich auch schon alle, die ich benötige. Ich versuche, das so zu definieren.

In [36]:
firmen_2007 = Firmen_07.head(5)
firmen_2007

   0        1        2       3            4                               5
12          0   10'000  18'759      996'701  7'098\n               \n73'685
13     10'100   50'000   4'028    7'654'106     258\n             \n367'378
14     50'100  250'000   2'636   28'215'316      93\n             \n594'332
15    250'100        +   1'723  487'465'494       31\n          \n1'057'921
16      Total           27'146  524'331'616    7'480\n          \n2'093'316

#### Headers setzen

In [39]:
headers = ['Weglassen', 'Steuerbarer Gewinn ab CHF', 'weglassen', 'Anzahl Steuerpflichtige 2007', 'Betrag Kantonssteuer 2007 in CHF', 
           'lassweg']

In [40]:
firmen_2007.columns = headers

In [41]:
firmen_2007

,Weglassen,Steuerbarer Gewinn ab CHF,weglassen,Anzahl Steuerpflichtige 2007,Betrag Kantonssteuer 2007 in CHF,lassweg
12,,0,10'000,18'759,996'701,7'098\n \n73'685
13,,10'100,50'000,4'028,7'654'106,258\n \n367'378
14,,50'100,250'000,2'636,28'215'316,93\n \n594'332
15,,250'100,+,1'723,487'465'494,31\n \n1'057'921
16,,Total,,27'146,524'331'616,7'480\n \n2'093'316

#### Die nicht benötigten Kolonnen wegschneiden

In [53]:
del firmen_2007['Weglassen']
del firmen_2007['weglassen']
del firmen_2007['lassweg']
firmen_2007

KeyError: 'Weglassen'

#### Ich putze den Datensatz (diese Strichli sind mir ein Dorn im Auge)

In [54]:
def geputzt(zeile):
    zeile = zeile.replace('(', '')
    zeile = zeile.replace(')', '')
    zeile = zeile.replace("'", "").strip()
    return zeile

In [55]:
firmen_2007['Steuerbarer Gewinn ab CHF'] = firmen_2007['Steuerbarer Gewinn ab CHF'].apply(geputzt)

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [56]:
firmen_2007

,Steuerbarer Gewinn ab CHF,Anzahl Steuerpflichtige 2007,Betrag Kantonssteuer 2007 in CHF
12,0,18'759,996'701
13,10100,4'028,7'654'106
14,50100,2'636,28'215'316
15,250100,1'723,487'465'494
16,Total,27'146,524'331'616

In [58]:
firmen_2007['Anzahl Steuerpflichtige 2007'] = firmen_2007['Anzahl Steuerpflichtige 2007'].apply(geputzt)
firmen_2007['Betrag Kantonssteuer 2007 in CHF'] = firmen_2007['Betrag Kantonssteuer 2007 in CHF'].apply(geputzt)
firmen_2007

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Steuerbarer Gewinn ab CHF,Anzahl Steuerpflichtige 2007,Betrag Kantonssteuer 2007 in CHF
12,0,18759,996701
13,10100,4028,7654106
14,50100,2636,28215316
15,250100,1723,487465494
16,Total,27146,524331616

#### Und dann möchte ich ja eigentlich die Kolonne Steuerbarer Gewinn als Header, und die Anzahl Steuerpflichtige und den Btrag der Kantonssteuer solls mir untendran stellen.

In [59]:
#Dazu ein paar Inspirationen aus Exploring und Plotting:
    
    # Mittelwerte 1909-1918 berechnen
#s_frueher = df_m.loc[1909:1918].mean()

#Mittelwerte 2009-2018 berechnen
#s_heute = df_m.loc[2009:2018].mean()

#Beide Mittelwertsreihen in Dataframe zusammenfügen
#df_v = pd.DataFrame({'Vor 100 Jahren': s_frueher, 'Heute': s_heute})

#So sieht das neue Dataframe aus
#df_v

#sowas könnte ich hier evtl auch machen

Oder: https://stackoverflow.com/questions/22173572/change-column-values-to-column-headers-in-pandas

Tipp von Manuela: mit xxxx.T kann ich eine Tabelle um 90 Grad drehen.

In [60]:
firmen_07 = firmen_2007.T
firmen_07

,12,13,14,15,16
Steuerbarer Gewinn ab CHF,0,10100,50100,250100,Total
Anzahl Steuerpflichtige 2007,18759,4028,2636,1723,27146
Betrag Kantonssteuer 2007 in CHF,996701,7654106,28215316,487465494,524331616

In [61]:
Firmen07 = firmen_07[1:]
Firmen07

,12,13,14,15,16
Anzahl Steuerpflichtige 2007,18759,4028,2636,1723,27146
Betrag Kantonssteuer 2007 in CHF,996701,7654106,28215316,487465494,524331616

### Headers neu

In [62]:
headers = ['Steuerbarer Gewinn 0-10000 CHF', 'Steuerbarer Gewinn 10100-50000 CHF', 'Steuerbarer Gewinn 50100-250000 CHF', 
           'Steuerbarer Gewinn ab 250100 CHF', 'Total Steuerbarer Gewinn']
Firmen07.columns = headers
Firmen07

,Steuerbarer Gewinn 0-10000 CHF,Steuerbarer Gewinn 10100-50000 CHF,Steuerbarer Gewinn 50100-250000 CHF,Steuerbarer Gewinn ab 250100 CHF,Total Steuerbarer Gewinn
Anzahl Steuerpflichtige 2007,18759,4028,2636,1723,27146
Betrag Kantonssteuer 2007 in CHF,996701,7654106,28215316,487465494,524331616

### Tabelle auseinander nehmen

In [76]:
Betrag_Kantonssteuer_2007 = Firmen07.drop(['Anzahl Steuerpflichtige 2007'])
Betrag_Kantonssteuer_2007

,Steuerbarer Gewinn 0-10000 CHF,Steuerbarer Gewinn 10100-50000 CHF,Steuerbarer Gewinn 50100-250000 CHF,Steuerbarer Gewinn ab 250100 CHF,Total Steuerbarer Gewinn
Betrag Kantonssteuer 2007 in CHF,996701,7654106,28215316,487465494,524331616

In [77]:
Anzahl_Steuerpflichtige_2007 = Firmen07.drop(['Betrag Kantonssteuer 2007 in CHF'])
Anzahl_Steuerpflichtige_2007

,Steuerbarer Gewinn 0-10000 CHF,Steuerbarer Gewinn 10100-50000 CHF,Steuerbarer Gewinn 50100-250000 CHF,Steuerbarer Gewinn ab 250100 CHF,Total Steuerbarer Gewinn
Anzahl Steuerpflichtige 2007,18759,4028,2636,1723,27146

Weiter im zweiten Testfile