In [1]:
import camelot
import tabula
import pandas as pd

# Schritt 1: PDF Verkehrsunfälle

In [2]:
tables_stream = camelot.read_pdf("Verkehrsunfälle2018.pdf", flavor='stream', pages='all', table_areas=['0,842,595,0'])

In [3]:
ff = pd.DataFrame() #=meine leere df

headers = ['Gemeinde', 'Sachschaden', 'Personenschaden', 'Getötete', 
           'Schwerverletzte', 'Lebensbedrohlich Verletzte', 
           'Erheblich Verletzte', 'Leichtverletzte'] #=meine Headers

#Und nun durch alles iterieren
#https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
for number in range(0,8):
    temporary = tables_stream[number].df #hier sagen wir, immer vorwärts gehen zur nächsten seite
    temporary = temporary[9:] #hier sagen wir: aber im fall erst ab der 9. reihe
    temporary.columns = headers #und dann setz uns bitte noch diese headers, die wir da definitert haben
    frames = [ff, temporary]  #so kleben wir eine tabelle an die andere an. ff ist ein neues frame, temp ist unsere einzelne tabelle oben
    ff = pd.concat(frames)   #mit concat kommts dann in die richtige form

In [4]:
def clean(elem):
    if elem == "": #wenn das element ein leerer string ist, gibt mir 0 zurück
        return 0
    else:
        return elem #sonst gib mir das element zurück
    
ff = ff.applymap(clean)

In [5]:
## Die Gemeinden zwischenzeitlich löschen und dann wieder reinnehmen bei der Umwandlung in Zahlen
gem = ff['Gemeinde'] 
del ff['Gemeinde'] #damit schneide ich die Kolonne "Gmeinde" ab

#für das noch überbleibende Dataframe wandle ich alle Strings in Integer
ff = ff.astype(int)

#und setze die Gemeinde-Kolonne wieder rein.
ff['Gemeinde'] = gem

#und definiere auch gleich die Reihenfolge der Headers, was hier aber nur Kosmetik ist
ff = ff[['Gemeinde', 'Sachschaden', 'Personenschaden', 'Getötete', 
           'Schwerverletzte', 'Lebensbedrohlich Verletzte', 
           'Erheblich Verletzte', 'Leichtverletzte']].copy()

In [6]:
ff = ff.reset_index() #so läuft das von 1 an durch dann, nicht erst ab 9
del ff['index']

In [14]:
dfunfälle=ff[:-1]

In [15]:
del dfunfälle['Lebensbedrohlich Verletzte']
del dfunfälle['Erheblich Verletzte']
dfunfälle.tail(5)

,Gemeinde,Sachschaden,Personenschaden,Getötete,Schwerverletzte,Leichtverletzte
341,Zielebach,1,0,0,0,0
342,Zollikofen,21,15,1,4,10
343,Zuzwil (BE),0,0,0,0,0
344,Zweisimmen,6,5,1,1,4
345,Zwieselberg,1,1,0,1,0

In [16]:
dfunfälle.tail(5)

,Gemeinde,Sachschaden,Personenschaden,Getötete,Schwerverletzte,Leichtverletzte
341,Zielebach,1,0,0,0,0
342,Zollikofen,21,15,1,4,10
343,Zuzwil (BE),0,0,0,0,0
344,Zweisimmen,6,5,1,1,4
345,Zwieselberg,1,1,0,1,0

# Schritt 2: PDF Einwohnerzahlen

In [18]:
einwohnerzahlen = camelot.read_pdf('EinwohnerzahlenKantonBern.pdf', flavor='stream', pages='all', table_areas=['0,842,595,0'])
einwohnerzahlen

In [20]:
#Ich lasse die Sache mit den Headers weg, weil die Kolonnenzahl unterschiedlich war
#Ausserdem schneide ich die letzte Zeile auch noch gleich weg.

ffeinwohnerzahlen = pd.DataFrame() #=meine leere df

        
#Und nun durch alles iterieren
#https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
for seite in range(0,4):
    temporaer = einwohnerzahlen[seite].df #hier sagen wir, immer vorwärts gehen zur nächsten seite
    temporaer = temporaer[4:99] #hier sagen wir: aber im fall erst ab der 4. reihe
    frameseinwohnerzahlen = [ffeinwohnerzahlen, temporaer]  #so kleben wir eine tabelle an die andere an. ff ist ein neues frame, temp ist unsere einzelne tabelle oben
    ffeinwohnerzahlen = pd.concat(frameseinwohnerzahlen)   #mit concat kommts dann in die richtige formffeinwohnerzahlen = pd.DataFrame() #=meine leere df

In [21]:
# dann schnappe ich mir nur die zweil Kolonnen raus, die mich interessieren
einwohnerzahlenneu = ffeinwohnerzahlen.iloc[:, [1,5]]

In [24]:
#jetzt mach ich noch dass die Tabelle bei 0 beginnt und nicht bei 4 (reset index)
einwohnerzahlenneu = einwohnerzahlenneu.reset_index() #so läuft das von 1 an durch dann, nicht erst ab 9
del einwohnerzahlenneu['index'] #und so lösche ich dann die index-kolonne, die index heisst und nun nicht mehr nötig ist

In [26]:
# und sage denen, wie sie heissen sollen
headerseinwohnerzahlenneu = ['Gemeinde','Einwohnerzahl 2018']
einwohnerzahlenneu.columns = headerseinwohnerzahlenneu

In [27]:
#Um die beiden Tabellen zu mergen, muss die Gemeindespalte der Einwohner-Tabelle bearbeitet werden.
#In jeder Zelle müssen die ersten vier Stellen abgeschnitten werden.
def cutstring(string):
    string = string[4:]
    return string
var = "301 Aarberg"
cutstring(var)

'Aarberg'

In [28]:
#jetzt für alle
einwohnerzahlenneu['Gemeinde'] = einwohnerzahlenneu['Gemeinde'].apply(cutstring)

In [29]:
einwohnerzahlenneu

                  Gemeinde                        Einwohnerzahl 2018
0                  Aarberg                                     4'628
1                Aarwangen                                     4'561
2                Adelboden                                     3'390
3                 Aefligen                                     1'090
4                 Aegerten                                     2'159
5         Aeschi bei Spiez                                     2'217
6    Affoltern im Emmental                                     1'101
7              Alchenstorf                                       575
8             Allmendingen                                       590
9              Amsoldingen                                       812
10                    Arch                                     1'594
11                 Arni BE                                       928
12                Attiswil                                     1'505
13                  Auswil                                       439
14                 Bannwil                                       669
15             Bargen (BE)                                       999
16                Bäriswil                                     1'062
17            Bätterkinden                                     3'250
18              Beatenberg                                     1'195
19                Bellmund                                     1'689
20                    Belp                                    11'510
21               Belprahon                                       294
22                  Berken                                        45
23                    Bern                                   133'883
24            Bettenhausen                                       631
25           Biel / Bienne                                    55'159
26                  Biglen                                     1'815
27              Bleienbach                                       697
28             Blumenstein                                     1'246
29                Bolligen                                     6'264
..                     ...                                       ...
319   Walliswil bei Wangen                                       608
320             Walperswil                                     1'043
321        Walterswil (BE)                                       538
322     Wangen an der Aare                                     2'312
323             Wangenried                                       425
324              Wattenwil                                     2'936
325                  Wengi                                       613
326              Wichtrach                                     4'293
327            Wiedlisbach                                     2'377
328              Wiggiswil                                       103
329             Wilderswil                                     2'658
330   Wiler bei Utzenstorf                                       963
331           Wileroltigen                                       360
332            Willadingen                                       205
333                 Wimmis                                     2'537
334        Wohlen bei Bern                                     9'282
335             Wolfisberg                                       184
336                   Worb                                    11'316
337                 Worben                                     2'287
338                  Wynau                                     1'628
339                Wynigen                                     2'060
340              Wyssachen                                     1'138
341                Zäziwil                                     1'595
342              Zielebach                                       321
343             Zollikofen                                    10'306
344            Zuzwil (BE)                                       578
345             Zweisimmen                                     3'018
346            Zwieselberg                                       332
347                         1'034'977 Total Einwohner per 31.12.2018
348

[349 rows x 2 columns]

Das ist schon mal ganz gut. Wie ich beim Mergen, dem nächsten Schritt, sehe, hauts mir ein paar Zahlen raus. Das liegt wohl an diesem doofen Apostroph, das verhindert, dass Python die Chose als Integer einordnen kann (jedenfalls hats mir auch ein paarmal eine Fehlermeldung gegeben, als ich das ändern wollte.) Wie ich das löse, finde ich später raus. Zuerst merge ich das hier noch zusammen, damit ich den nächsten Schritt hätte. Die NaNs putze ich dann mir frischerem Kopf wieder raus. Und am besten nehme ich das hier als Grundlage.

# Schritt 3: Mergen

In [30]:
pd.merge(dfunfälle,einwohnerzahlenneu,
         how ='left',on='Gemeinde')

,Gemeinde,Sachschaden,Personenschaden,Getötete,Schwerverletzte,Leichtverletzte,Einwohnerzahl 2018
0,Aarberg,26,12,0,2,15,4'628
1,Aarwangen,10,15,0,2,14,4'561
2,Adelboden,8,11,1,3,9,3'390
3,Aefligen,0,0,0,0,0,1'090
4,Aegerten,3,3,0,0,4,2'159
5,Aeschi bei Spiez,9,6,0,2,5,2'217
6,Affoltern im Emmental,3,4,0,0,4,1'101
7,Alchenstorf,1,1,0,0,2,575
8,Allmendingen,5,3,0,2,1,590
9,Amsoldingen,2,0,0,0,0,812
10,Arch,1,2,0,0,2,1'594
11,Arni (BE),2,1,0,0,1,NaN
12,Attiswil,2,1,0,0,1,1'505
13,Auswil,1,0,0,0,0,439
14,Bannwil,1,1,0,1,0,669
15,Bargen (BE),2,4,0,0,4,999
16,Bäriswil,1,3,0,0,5,1'062
17,Bätterkinden,4,6,0,0,7,3'250
18,Beatenberg,4,4,0,0,5,1'195
19,Bellmund,1,0,0,0,0,1'689
20,Belp,25,30,0,5,27,11'510
21,Belprahon,1,0,0,0,0,294
22,Berken,0,1,0,1,0,45
23,Bern,353,345,5,69,333,133'883
24,Bettenhausen,2,1,0,0,1,631
25,Biel/Bienne,196,201,1,23,193,NaN
26,Biglen,1,1,0,1,0,1'815
27,Bleienbach,5,2,0,0,2,697
28,Blumenstein,0,4,0,2,3,1'246
29,Bolligen,13,7,0,2,5,6'264
...,...,...,...,...,...,...,...
316,Walkringen,4,6,0,1,5,1'767
317,Walliswil bei Niederbipp,2,1,0,2,1,211
318,Walliswil bei Wangen,2,1,0,0,1,608
319,Walperswil,3,0,0,0,0,1'043
320,Walterswil (BE),0,1,0,0,1,538
321,Wangen an der Aare,4,2,0,1,2,2'312
322,Wangenried,0,0,0,0,0,425
323,Wattenwil,1,5,0,0,5,2'936
324,Wengi,3,4,0,1,3,613
325,Wichtrach,5,13,0,5,11,4'293
326,Wiedlisbach,13,5,0,0,10,2'377
327,Wiggiswil,0,1,0,0,2,103
328,Wilderswil,13,11,0,1,16,2'658
329,Wiler bei Utzenstorf,0,3,0,2,1,963
330,Wileroltigen,1,0,0,0,0,360
331,Willadingen,1,0,0,0,0,205
332,Wimmis,5,3,0,0,3,2'537
333,Wohlen bei Bern,8,9,0,2,14,9'282
334,Wolfisberg,0,0,0,0,0,184
335,Worb,19,23,0,2,27,11'316
336,Worben,4,2,0,1,1,2'287
337,Wynau,2,4,0,0,4,1'628
338,Wynigen,6,10,0,2,9,2'060
339,Wyssachen,0,2,1,1,0,1'138
340,Zäziwil,2,1,0,0,1,1'595
341,Zielebach,1,0,0,0,0,321
342,Zollikofen,21,15,1,4,10,10'306
343,Zuzwil (BE),0,0,0,0,0,578
344,Zweisimmen,6,5,1,1,4,3'018
345,Zwieselberg,1,1,0,1,0,332